version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci

  pre_build:
    commands:
      - npm run lint || (echo "Linting completed with warnings" && exit 0)

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully"
      - aws s3 sync dist/ s3://${S3_BUCKET_NAME}/ --delete
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  name: hr-ui-build-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - 'node_modules/**/*' 